# Netlify Configuration for HTML/CSS Portfolio
# This site is a static HTML/CSS/JS portfolio - no build step required

[build]
  # No build command needed for static HTML
  publish = "."

# Redirect rules
[[redirects]]
  from = "/showreel"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Plugins for quality checks - DISABLED temporarily to allow deployment
# Re-enable after adding all assets
# [[plugins]]
#   package = "netlify-plugin-checklinks"
#   [plugins.inputs]
#     skipPatterns = ["https://fonts.googleapis.com", "https://fonts.gstatic.com", "https://www.youtube.com"]

# [[plugins]]
#   package = "@netlify/plugin-lighthouse"
#   [plugins.inputs]
#     # Run Lighthouse audits
#     audits = ["performance", "accessibility", "best-practices", "seo"]
