# Netlify Configuration for HTML/CSS Portfolio
# This site is a static HTML/CSS/JS portfolio - no build step required

[build]
  # No build command needed for static HTML
  publish = "."
  ignore = "false"

[build.environment]
  NODE_VERSION = "18"
  # Disable all build plugins
  NETLIFY_USE_YARN = "false"

# Redirect rules
[[redirects]]
  from = "/showreel"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# IMPORTANT: All plugins are DISABLED
# The build was failing due to plugins checking for missing files
# Plugins can be re-enabled after all assets are added

# To override any plugins configured in Netlify UI, we explicitly set an empty plugins array
# This tells Netlify to ignore any UI-configured plugins
