[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20.18.0"

[[plugins]]
  package = "netlify-plugin-checklinks"

  [plugins.inputs]
    skipPatterns = [
      "preconnect-check https://fonts.googleapis.com",
      "preconnect-check https://fonts.gstatic.com",
    ]
